config/routes.rb
Rails.application.routes.draw do
  
  resources :fichans
  resources :ficha_nacionals
  resources :localidads
  resources :countries
  resources :proveedors
  resources :constants
  resources :permissions do
    get 'userlist', on: :collection
    get 'usersregistrated', on: :collection
    get 'recoverpassword', on: :collection
    get 'recoveradmin', on: :collection
    get 'listrecoveradmin', on: :collection
  end
  resources :sectors
  resources :areas
  resources :calls do
    get 'search', on: :collection
  end
  devise_for :users, controllers: {registrations: 'registrations'}

  
  get 'welcome/index'

  root 'welcome#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :sectors

end

app/models/call.rb
class Call < ActiveRecord::Base

	belongs_to :user


#	attr_accessor :incoming, :outgoing, :call_date, :call_time, :extension, :dial_number, :ring, :duration
#    attr_accessor :acc_code, :cd, :cost, :co



#	validates :call_date,
#  					presence:true
# 	validates :call_time,
# 					presence:true
# 	validates :extension,
# 					presence:true
# 	validates :dial_number,
# 					presence:true
# 	validates :co,
# 					presence:true
# 	validates :cd,
# 					presence:true
# 	validates :call_date,
# 					presence:true
# 	validates :incoming,
# 					presence:true
# 	validates :outgoing,
# 					presence:true
# 	validates :ring,
#jhf		presence:true
#  	 				validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}
 # 	validates :duration,
  #					presence:true
  #	validates :cost,
  #					presence:true,
# 	 				validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}
  #	validates :acc_code,
  #					presence:true,
#					validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}

	
end

app/models/constant.rb
class Constant < ActiveRecord::Base

	belongs_to :proveedor
	has_many :ficha_nacionals

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/ficha_nacional.rb
class FichaNacional < ActiveRecord::Base
	belongs_to :constant
end

app/models/fichan.rb
class Fichan < ActiveRecord::Base
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base

	belongs_to :user
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base

	has_one :constant

end

app/models/sector.rb
class Sector < ActiveRecord::Base
	belongs_to :area
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :sector
  has_many :calls
  has_one :perimission



end

app/controllers/ficha_nacionals_controller.rb
class FichaNacionalsController < ApplicationController
  before_action :set_ficha_nacional, only: [:show, :edit, :update, :destroy]

  # GET /ficha_nacionals
  # GET /ficha_nacionals.json
  def index
    @ficha_nacionals = FichaNacional.all
  end

  # GET /ficha_nacionals/1
  # GET /ficha_nacionals/1.json
  def show
  end

  # GET /ficha_nacionals/new
  def new
    @ficha_nacional = FichaNacional.new
  end

  # GET /ficha_nacionals/1/edit
  def edit
  end

  # POST /ficha_nacionals
  # POST /ficha_nacionals.json
  def create
    @ficha_nacional = FichaNacional.new(ficha_nacional_params)

    respond_to do |format|
      if @ficha_nacional.save
        format.html { redirect_to @ficha_nacional, notice: 'Ficha nacional was successfully created.' }
        format.json { render :show, status: :created, location: @ficha_nacional }
      else
        format.html { render :new }
        format.json { render json: @ficha_nacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ficha_nacionals/1
  # PATCH/PUT /ficha_nacionals/1.json
  def update
    respond_to do |format|
      if @ficha_nacional.update(ficha_nacional_params)
        format.html { redirect_to @ficha_nacional, notice: 'Ficha nacional was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha_nacional }
      else
        format.html { render :edit }
        format.json { render json: @ficha_nacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ficha_nacionals/1
  # DELETE /ficha_nacionals/1.json
  def destroy
    @ficha_nacional.destroy
    respond_to do |format|
      format.html { redirect_to ficha_nacionals_url, notice: 'Ficha nacional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha_nacional
      @ficha_nacional = FichaNacional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_nacional_params
      params.require(:ficha_nacional).permit(:code, :valor_seg, :valor_min, :constante_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/calls_helper.rb
module CallsHelper





end

app/helpers/constants_helper.rb
module ConstantsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/ficha_nacionals_helper.rb
module FichaNacionalsHelper
end

app/helpers/fichans_helper.rb
module FichansHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/proovedors_helper.rb
module ProovedorsHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ficha_nacionals/_form.html.erb
<%= form_for(@ficha_nacional) do |f| %>
  <% if @ficha_nacional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ficha_nacional.errors.count, "error") %> prohibited this ficha_nacional from being saved:</h2>

      <ul>
      <% @ficha_nacional.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interurbano %><br>
    <%= f.number_field :interurbano %>
  </div>
  <div class="field">
    <%= f.label :valor_seg %><br>
    <%= f.text_field :valor_seg %>
  </div>
  <div class="field">
    <%= f.label :valor_min %><br>
    <%= f.text_field :valor_min %>
  </div>
  <div class="field">
    <%= f.label :constant_id %><br>
    <%= f.number_field :constant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ficha_nacionals/edit.html.erb
<h1>Editing Ficha Nacional</h1>

<%= render 'form' %>

<%= link_to 'Show', @ficha_nacional %> |
<%= link_to 'Back', ficha_nacionals_path %>

app/views/ficha_nacionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ficha Nacionals</h1>

<table>
  <thead>
    <tr>
      <th>Interurbano</th>
      <th>Valor seg</th>
      <th>Valor min</th>
      <th>Constant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ficha_nacionals.each do |ficha_nacional| %>
      <tr>
        <td><%= ficha_nacional.interurbano %></td>
        <td><%= ficha_nacional.valor_seg %></td>
        <td><%= ficha_nacional.valor_min %></td>
        <td><%= ficha_nacional.constant_id %></td>
        <td><%= link_to 'Show', ficha_nacional %></td>
        <td><%= link_to 'Edit', edit_ficha_nacional_path(ficha_nacional) %></td>
        <td><%= link_to 'Destroy', ficha_nacional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ficha nacional', new_ficha_nacional_path %>

app/views/ficha_nacionals/new.html.erb
<h1>New Ficha Nacional</h1>

<%= render 'form' %>

<%= link_to 'Back', ficha_nacionals_path %>

app/views/ficha_nacionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interurbano:</strong>
  <%= @ficha_nacional.interurbano %>
</p>

<p>
  <strong>Valor seg:</strong>
  <%= @ficha_nacional.valor_seg %>
</p>

<p>
  <strong>Valor min:</strong>
  <%= @ficha_nacional.valor_min %>
</p>

<p>
  <strong>Constant:</strong>
  <%= @ficha_nacional.constant_id %>
</p>

<%= link_to 'Edit', edit_ficha_nacional_path(@ficha_nacional) %> |
<%= link_to 'Back', ficha_nacionals_path %>