config/routes.rb
Rails.application.routes.draw do
  
  resources :fichans
  resources :ficha_nacionals
  resources :localidads
  resources :countries
  resources :proveedors
  resources :constants
  resources :permissions do
    get 'userlist', on: :collection
    get 'usersregistrated', on: :collection
    get 'recoverpassword', on: :collection
    get 'recoveradmin', on: :collection
    get 'listrecoveradmin', on: :collection
  end
  resources :sectors
  resources :areas
  resources :calls do
    get 'search', on: :collection
  end
  devise_for :users, controllers: {registrations: 'registrations'}

  
  get 'welcome/index'

  root 'welcome#index'

end

app/models/call.rb
class Call < ActiveRecord::Base

	belongs_to :user


#	attr_accessor :incoming, :outgoing, :call_date, :call_time, :extension, :dial_number, :ring, :duration
#    attr_accessor :acc_code, :cd, :cost, :co



#	validates :call_date,
#  					presence:true
# 	validates :call_time,
# 					presence:true
# 	validates :extension,
# 					presence:true
# 	validates :dial_number,
# 					presence:true
# 	validates :co,
# 					presence:true
# 	validates :cd,
# 					presence:true
# 	validates :call_date,
# 					presence:true
# 	validates :incoming,
# 					presence:true
# 	validates :outgoing,
# 					presence:true
# 	validates :ring,
#jhf		presence:true
#  	 				validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}
 # 	validates :duration,
  #					presence:true
  #	validates :cost,
  #					presence:true,
# 	 				validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}
  #	validates :acc_code,
  #					presence:true,
#					validates_exclusion_of: in:{ with: /\A[a-zA-Z]+\z/}

	
end

app/controllers/calls_controller.rb
require "prawn"

class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]


=begin
  def search
    @tipo = params[:tipo]
    @destino = params[:destino]
    if (current_user.admin?)
      @area = params[:area]
      @sector = params[:sector]
      @interno = params[:interno]
    else 
      @area= current_user.area
      @sector= current_user.sector
      @interno = current_user.internal
    end
    ini = params[:fechaini]
    fin = params[:fechafin]
    if (ini > fin)
      flash[:notice] = "La fecha inicial no puede ser mayor a la final"
    elsif ((!interno.blank?) && (sector.blank?)) || ((!interno.blank?) && (area.blank?))
      flash[:notice] = "Si se ingresa un interno debe ingresar el sector y area"
    elsif (Area.where(name: @area).count == 0) && (!@area.blank?)
      flash[:notice] = "El area ingresada no es correcta"
    elsif (Sector.where(name: @sector).count == 0) && (!@sector.blank?)
      flash[:notice] = "El sector ingresado no es correcta"
    else
      @calls = Call.where("? <= created_at AND created_at <= ? ",ini, fin)
    end
  end

=end


  def search


  end

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = Call.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text "Hello World"
        send_data pdf.render, filename: "llamada: #{@call.id}.pdf",
                            type: "application/pdf",
                            disposition: "inline"

      end
    end

  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:incoming, :outgoing, :call_date, :call_time, :extension, :dial_number, :ring, :duration, :acc_code, :cd, :cost)
    end
end

app/helpers/calls_helper.rb
module CallsHelper





end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :incoming %><br>
    <%= f.check_box :incoming %>
  </div>
  <div class="field">
    <%= f.label :outgoing %><br>
    <%= f.check_box :outgoing %>
  </div>
  <div class="field">
    <%= f.label :call_date %><br>
    <%= f.date_select :call_date %>
  </div>
  <div class="field">
    <%= f.label :call_time %><br>
    <%= f.time_select :call_time %>
  </div>
  <div class="field">
    <%= f.label :extension %><br>
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :dial_number %><br>
    <%= f.text_field :dial_number %>
  </div>
  <div class="field">
    <%= f.label :ring %><br>
    <%= f.number_field :ring %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :acc_code %><br>
    <%= f.number_field :acc_code %>
  </div>
  <div class="field">
    <%= f.label :cd %><br>
    <%= f.text_field :cd %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/_searchoption.html.erb
<%@calls = Call.where("? <= created_at AND created_at <= ? ", @ini, @fin) %>
<%if @calls.count > 0 %>

<% if @tipo == "entrante" %>
  <% u=true %>
<%else%>
  <% u=false %>
<%end%>

<%if (@destino.blank?) && (@area.blank?)  %>
  <%calls = @calls.where(incoming:"#{u}" )%> 
  <%elsif (@area.blank?) && (@tipo.blank?) %>
    <%calls = @calls.where(destiny:"#{@destino}")%> 
    <%elsif (@interno.blank?) && (@destino.blank?) %>
      <%if @sector.blank? %>
        <%calls = @calls.where(area_id: @area.id)%>
        <%elsif @interno.blank? %>
          <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id)%>
          <%else%>
            <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id, internal: @interno)%>
      <%end%>
      <%elsif @tipo.blank?%>
        <%if @sector.blank? %>
          <%calls = @calls.where(area_id: @area.id, destiny:  "#{@destino}")%>
        <%elsif @interno.blank? %>
          <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id, destiny:  "#{@destino}")%>
          <%else%>
            <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id, internal: @interno, destiny:  "#{@destino}")%>
        <%end%>
        <%elsif @destino.blank?%>
          <%if @sector.blank? %>
            <%calls = @calls.where(area_id: @area.id, incoming: u)%>
          <%elsif @interno.blank? %>
            <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id, incoming: u)%>
            <%else%>
              <%calls = @calls.where(area_id: @area.id, sector_id: @sector.id, internal: @interno, incoming: u)%>
          <%end%>
        <%else @area.blank?%>
          <%calls = @calls.where(incoming: u, destiny: "#{@destino}")%>
<%end%>







<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Busqueda de Llamadas
  </div>
</div>


<div class="panel panel-success">
  <div class="panel-body">
    <div class="row">
      <table class="table table-bordered">
        <thead>
        <tr>
       	  <th>Tipo de LLamada</th> 	
          <th>Numero de Dial</th>
          <th>Fecha</th>
          <th>Hora</th>
          <th>Tiempo de Espera</th>
          <th>Duracion</th>
          <th>Costo</th>
        </tr>
        </thead>

        <tbody>
          <% calls.each do |call| %>
              <tr>
              	<% if call.incoming? %>
                	<td>Entrante</td>
                <%else%>
                	<td>Saliente</td>
                <%end%>
                <td><%= call.dial_number %></td>
                <td><%= call.call_date %></td>
                <td><%= call.call_time %></td>
                <td><%= call.ring %></td>
                <td><%= call.duration %></td>
                <td><%= call.cost %></td>              
              </tr>
          <%end%>
        </tbody>
      </table>        
      <br>
    </div>
    <%= link_to "Imprimir Busqueda", search_calls_path(calls, format: "pdf") %>
  </div>
</div>

<%end%>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Incoming</th>
      <th>Outgoing</th>
      <th>Call date</th>
      <th>Call time</th>
      <th>Extension</th>
      <th>Dial number</th>
      <th>Ring</th>
      <th>Duration</th>
      <th>Acc code</th>
      <th>Cd</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.incoming %></td>
        <td><%= call.outgoing %></td>
        <td><%= call.call_date %></td>
        <td><%= call.call_time %></td>
        <td><%= call.extension %></td>
        <td><%= call.dial_number %></td>
        <td><%= call.ring %></td>
        <td><%= call.duration %></td>
        <td><%= call.acc_code %></td>
        <td><%= call.cd %></td>
        <td><%= call.cost %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New Call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/search.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Busqueda de Llamadas</h3>
      </div>
      <div class="panel-body">
      <%= form_tag '/calls/search', :method=>"get" do %>
      <form>
       <div class="form-group">
        <%= label_tag :tipo, 'Seleccione tipo de llamada' %>
        <%= select_tag :tipo, options_for_select(["Seleccionar opcion", "entrante", "saliente"],:disabled => ["Seleccionar opcion"]), :class => 'genForm_dropBox' %>
      </div>
      <div class="form-group">
        <%= label_tag :destino, 'Seleccione destino de llamada' %>
        <%= select_tag :destino, options_for_select(["Seleccionar opcion", "internacional", "nacional", "local","celular"],:disabled => ["Seleccionar opcion"]), :class => 'genForm_dropBox' %>
      </div>


      <%if current_user.admin?%>
      <div class="form-group">
        <%= label_tag :area, "Area" %></br>
        <%= text_field_tag :area, '',required: true, autofocus: true, class:"form-control"%>
       </div>
      <div class="form-group">
        <%=label_tag :sector, "sector" %></br>
        <%= text_field_tag :sector, '',required: true, autofocus: true, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= label_tag :interno, 'Ingrese interno' %>
        <%= number_field_tag :interno, '',autofocus: true, class:"form-control"%>
      </div>
      <%end%>


      <div class="form-group">
        <%= label_tag :fechahini, 'Ingrese fecha inicial' %>
        <%= date_field_tag :fechaini, '',required: true, autofocus: true, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= label_tag :fechafin, 'Ingrese fecha final'%>
        <%= date_field_tag :fechafin, '',required: true, autofocus: true, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= submit_tag 'Buscar', class: "btn btn-success btn-block" %>
      </div>
      </form>
      <% end %>
    </div>
  </div>
</div>
</div>


<%= render 'searchoption' %>
  

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Incoming:</strong>
  <%= @call.incoming %>
</p>

<p>
  <strong>Outgoing:</strong>
  <%= @call.outgoing %>
</p>

<p>
  <strong>Call date:</strong>
  <%= @call.call_date %>
</p>

<p>
  <strong>Call time:</strong>
  <%= @call.call_time %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @call.extension %>
</p>

<p>
  <strong>Dial number:</strong>
  <%= @call.dial_number %>
</p>

<p>
  <strong>Ring:</strong>
  <%= @call.ring %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @call.duration %>
</p>

<p>
  <strong>Acc code:</strong>
  <%= @call.acc_code %>
</p>

<p>
  <strong>Cd:</strong>
  <%= @call.cd %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @call.cost %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>

<p><%= link_to "Printable Receipt (PDF)", call_path(@call, format: "pdf") %>
 </p>