config/routes.rb
Rails.application.routes.draw do
  
  resources :fichans
  resources :ficha_nacionals
  resources :localidads
  resources :countries
  resources :proveedors
  resources :constants
  resources :permissions do
    get 'userlist', on: :collection
    get 'usersregistrated', on: :collection
    get 'recoverpassword', on: :collection
    get 'recoveradmin', on: :collection
    get 'listrecoveradmin', on: :collection
  end
  resources :sectors
  resources :areas
  resources :calls do
    get 'search', on: :collection
  end
  devise_for :users, controllers: {registrations: 'registrations'}

  
  get 'welcome/index'

  root 'welcome#index'

end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
end

app/controllers/localidads_controller.rb
class LocalidadsController < ApplicationController
  before_action :set_localidad, only: [:show, :edit, :update, :destroy]

  # GET /localidads
  # GET /localidads.json
  def index
    @localidads = Localidad.all
  end

  # GET /localidads/1
  # GET /localidads/1.json
  def show
  end

  # GET /localidads/new
  def new
    @localidad = Localidad.new
  end

  # GET /localidads/1/edit
  def edit
  end

  # POST /localidads
  # POST /localidads.json
  def create
    @localidad = Localidad.new(localidad_params)

    respond_to do |format|
      if @localidad.save
        format.html { redirect_to @localidad, notice: 'Localidad was successfully created.' }
        format.json { render :show, status: :created, location: @localidad }
      else
        format.html { render :new }
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localidads/1
  # PATCH/PUT /localidads/1.json
  def update
    respond_to do |format|
      if @localidad.update(localidad_params)
        format.html { redirect_to @localidad, notice: 'Localidad was successfully updated.' }
        format.json { render :show, status: :ok, location: @localidad }
      else
        format.html { render :edit }
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localidads/1
  # DELETE /localidads/1.json
  def destroy
    @localidad.destroy
    respond_to do |format|
      format.html { redirect_to localidads_url, notice: 'Localidad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localidad
      @localidad = Localidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localidad_params
      params.require(:localidad).permit(:name, :code)
    end
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/views/localidads/_form.html.erb
<%= form_for(@localidad) do |f| %>
  <% if @localidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@localidad.errors.count, "error") %> prohibited this localidad from being saved:</h2>

      <ul>
      <% @localidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :interurbano %><br>
    <%= f.number_field :interurbano %>
  </div>
  <div class="field">
    <%= f.label :clave_nqn %><br>
    <%= f.number_field :clave_nqn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localidads/edit.html.erb
<h1>Editing Localidad</h1>

<%= render 'form' %>

<%= link_to 'Show', @localidad %> |
<%= link_to 'Back', localidads_path %>

app/views/localidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Localidads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Interurbano</th>
      <th>Clave nqn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localidads.each do |localidad| %>
      <tr>
        <td><%= localidad.name %></td>
        <td><%= localidad.interurbano %></td>
        <td><%= localidad.clave_nqn %></td>
        <td><%= link_to 'Show', localidad %></td>
        <td><%= link_to 'Edit', edit_localidad_path(localidad) %></td>
        <td><%= link_to 'Destroy', localidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Localidad', new_localidad_path %>

app/views/localidads/new.html.erb
<h1>New Localidad</h1>

<%= render 'form' %>

<%= link_to 'Back', localidads_path %>

app/views/localidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @localidad.name %>
</p>

<p>
  <strong>Interurbano:</strong>
  <%= @localidad.interurbano %>
</p>

<p>
  <strong>Clave nqn:</strong>
  <%= @localidad.clave_nqn %>
</p>

<%= link_to 'Edit', edit_localidad_path(@localidad) %> |
<%= link_to 'Back', localidads_path %>