config/routes.rb
Rails.application.routes.draw do
  
  resources :fichans
  resources :ficha_nacionals
  resources :localidads
  resources :countries
  resources :proveedors
  resources :constants
  resources :permissions do
    get 'userlist', on: :collection
    get 'usersregistrated', on: :collection
    get 'recoverpassword', on: :collection
    get 'recoveradmin', on: :collection
    get 'listrecoveradmin', on: :collection
  end
  resources :sectors
  resources :areas
  resources :calls do
    get 'search', on: :collection
  end
  devise_for :users, controllers: {registrations: 'registrations'}

  
  get 'welcome/index'

  root 'welcome#index'

end

app/models/fichan.rb
class Fichan < ActiveRecord::Base
end

app/controllers/fichans_controller.rb
class FichansController < ApplicationController
  before_action :set_fichan, only: [:show, :edit, :update, :destroy]

  # GET /fichans
  # GET /fichans.json
  def index
    @fichans = Fichan.all
  end

  # GET /fichans/1
  # GET /fichans/1.json
  def show
  end

  # GET /fichans/new
  def new
    @fichan = Fichan.new
  end

  # GET /fichans/1/edit
  def edit
  end

  # POST /fichans
  # POST /fichans.json
  def create
    @fichan = Fichan.new(fichan_params)

    respond_to do |format|
      if @fichan.save
        format.html { redirect_to @fichan, notice: 'Fichan was successfully created.' }
        format.json { render :show, status: :created, location: @fichan }
      else
        format.html { render :new }
        format.json { render json: @fichan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichans/1
  # PATCH/PUT /fichans/1.json
  def update
    respond_to do |format|
      if @fichan.update(fichan_params)
        format.html { redirect_to @fichan, notice: 'Fichan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fichan }
      else
        format.html { render :edit }
        format.json { render json: @fichan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichans/1
  # DELETE /fichans/1.json
  def destroy
    @fichan.destroy
    respond_to do |format|
      format.html { redirect_to fichans_url, notice: 'Fichan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fichan
      @fichan = Fichan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fichan_params
      params.require(:fichan).permit(:code, :valor_sec_n, :valor_sec_r, :valor_min_n, :valor_min_r, :description)
    end
end

app/helpers/fichans_helper.rb
module FichansHelper
end

app/views/fichans/_form.html.erb
<%= form_for(@fichan) do |f| %>
  <% if @fichan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fichan.errors.count, "error") %> prohibited this fichan from being saved:</h2>

      <ul>
      <% @fichan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :valor_sec_n %><br>
    <%= f.text_field :valor_sec_n %>
  </div>
  <div class="field">
    <%= f.label :valor_sec_r %><br>
    <%= f.text_field :valor_sec_r %>
  </div>
  <div class="field">
    <%= f.label :valor_min_n %><br>
    <%= f.text_field :valor_min_n %>
  </div>
  <div class="field">
    <%= f.label :valor_min_r %><br>
    <%= f.text_field :valor_min_r %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fichans/edit.html.erb
<h1>Editing Fichan</h1>

<%= render 'form' %>

<%= link_to 'Show', @fichan %> |
<%= link_to 'Back', fichans_path %>

app/views/fichans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fichans</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Valor sec n</th>
      <th>Valor sec r</th>
      <th>Valor min n</th>
      <th>Valor min r</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fichans.each do |fichan| %>
      <tr>
        <td><%= fichan.code %></td>
        <td><%= fichan.valor_sec_n %></td>
        <td><%= fichan.valor_sec_r %></td>
        <td><%= fichan.valor_min_n %></td>
        <td><%= fichan.valor_min_r %></td>
        <td><%= fichan.description %></td>
        <td><%= link_to 'Show', fichan %></td>
        <td><%= link_to 'Edit', edit_fichan_path(fichan) %></td>
        <td><%= link_to 'Destroy', fichan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fichan', new_fichan_path %>

app/views/fichans/new.html.erb
<h1>New Fichan</h1>

<%= render 'form' %>

<%= link_to 'Back', fichans_path %>

app/views/fichans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @fichan.code %>
</p>

<p>
  <strong>Valor sec n:</strong>
  <%= @fichan.valor_sec_n %>
</p>

<p>
  <strong>Valor sec r:</strong>
  <%= @fichan.valor_sec_r %>
</p>

<p>
  <strong>Valor min n:</strong>
  <%= @fichan.valor_min_n %>
</p>

<p>
  <strong>Valor min r:</strong>
  <%= @fichan.valor_min_r %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fichan.description %>
</p>

<%= link_to 'Edit', edit_fichan_path(@fichan) %> |
<%= link_to 'Back', fichans_path %>